{% set version = "0.3.0" %}

package:
  name: jupyterlite-javascript-kernel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlite-javascript-kernel/jupyterlite_javascript_kernel-{{ version }}.tar.gz
  sha256: 39870efb4cdfe669b99552b4ad21a82f575691e4fdaf77b33bef04ec230889ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version >=0.3.2
    - hatchling >=1.5.0
    - jupyterlab >=4.1.1,<4.2
    - pip
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - jupyterlite_javascript_kernel
  commands:
    - pip check
    - python -c "v = __import__('jupyterlite_javascript_kernel').__version__; print(v); assert v == '{{ version }}'"

  requires:
    - pip

about:
  home: https://github.com/jupyterlite/javascript-kernel
  summary: A JavaScript kernel for JupyterLite
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlite_javascript_kernel/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - bollwyvl
    - conda-forge/jupyterlite-core
